window.MIMI_SERVICES_ENV = {
  SUPABASE_URL: "https://xrphpqmutvadjrucqicn.supabase.co",
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhycGhwcW11dHZhZGpydWNxaWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ0MDY5ODgsImV4cCI6MjA4OTk4Mjk4OH0.0nsO3GBevQzMBCvne17I9L5_Yi4VPYiWedxyntLr4uM",
  VITE_POCKETBASE_URL: "https://cms.mimigo.com.ar",
  VITE_FINGERPRINT_ENABLED: true,
  VITE_FINGERPRINT_MODE: "audit",
  MIMI_DEFAULT_PHONE_COUNTRY: "AR",
  MIMI_POCKETBASE_TIMEOUT_MS: 2500,
  MIMI_REALTIME_ENABLED: true,
  MIMI_REMOTE_BOOTSTRAP_ENABLED: false,
  MIMI_BOOT_PUSH_REGISTRATION: true,
  SECURITY_FLAGS: {
    ENABLE_SECURITY_ANALYTICS: true
  },
  DEMO_CLIENT_USER_ID: null,
  DEMO_PROVIDER_USER_ID: null,
};
